### ISSUE TITLE
Spontaneous gender change

### ISSUE THREAD

**Issue by skylord-a52** [lizardqueenlexi/orbstation#103] opened 2022-07-03 05:17 UTC
There's some kind of mutation, random event, disease symptom, trauma, or something that randomly changed my gender in game today, with a message something like "You suddenly feel more masculine". It reverted itself a minute or two later with the message "You suddenly feel more feminine". I didn't stand in radiation, give myself mutations, sustain head damage, or become infected by a virus (to my knowledge), so I have no idea what caused it, and admins say it didn't leave a message in the event log.

I can see why this might be harmlessly interesting for a casual server of cis people, but for an rp-heavy server of mostly trans people, it's not great and should be removed, whatever it is.

**Comment by skylord-a52** [comment] 2022-07-03 05:22
Update: Discord discussions suggest this was the result of the light pink slime gender change potion, but... why did it randomly trigger? Who knows, unless possibly somebody did this to me secretly.

**Comment by lizardqueenlexi** [comment] 2022-07-03 23:17
As best I can tell, this was caused by someone specifically using the "gender change potion" item on you, something that inexplicably acts instantly and through any and all clothing with a single click. If it reverted, it means that a second one was also used on you. I'm working on a PR to make that item only work on the wielder instead of other people.

**Comment by lizardqueenlexi** [comment] 2022-07-04 06:38
Resolved by #106

**Closed by lizardqueenlexi** 2022-07-04 06:38 UTC
